parameters:

services:
    task_repository:
        class: ScrumBoard\Domain\TaskRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - ScrumBoard\Domain\Model\Task
